### ISSUE TITLE
running the lossless on own HPC

### ISSUE THREAD

**Issue by akaKinFish** [BUCANL/BIDS-Lossless-EEG#2]
Excuse me, cause I don't have the access to use computer Canada. So I need to build the remote in my own HPC. But I found some problems. When I running S05, got this

Error: support for FFTW was unavailable or disabled when liboctave was built
Stack trace:
	at /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-09-03T11-57-44/../../code/dependencies/eeglab_lossless/plugins/vised_marks/marks/measure_func/chan_variance.m(chan_variance:59)
	at /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-09-03T11-57-44/s05_concat_data_sub_010_task_faceFO_eeg.m(s05_concat_data_sub_010_task_faceFO_eeg:231)
	at /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/batch_context/batch/exec_func/octave_exit_wrapper.m(derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/batch_context/batch/exec_func/octave_exit_wrapper.m:69)

Maybe the environment is not completey. 
Octave is 5.2.0.

And another issue, could you please list the environment requirements with exact version? 

Looking forward for your reply.

**Comment by Andesha** [comment]
@SaraStephenson

**Comment by akaKinFish** [comment]
I solved this problem by re-compile the OCTAVE, but the S05 found another problem.

`Scanning terminated. Refining dipole locations...
INFO:	2021-09-18T15:41:50	540.394600	234.660194	pop_multifit_bucanl_parallel:148:	Searching dipoles locations...

warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
execution error
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
Error: __parcellfun_get_next_result__: could not receive result
Stack trace:
	at /home/yukin/octave/parallel-4.0.1/parcellfun.m(parcellfun:201)
	at /home/yukin/octave/parallel-4.0.1/pararrayfun.m(pararrayfun:85)
	at /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/functions/miscfunc/pop_multifit_bucanl_parallel.m(pop_multifit_bucanl_parallel:153)
	at /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/s05_concat_data_sub_002_task_faceFO_eeg.m(s05_concat_data_sub_002_task_faceFO_eeg:464)
	at /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/batch_context/batch/exec_func/octave_exit_wrapper.m(derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/batch_context/batch/exec_func/octave_exit_wrapper.m:69)`

Best wishes for you.

**Comment by akaKinFish** [comment]
I solved this problem by re-compile the OCTAVE, but found another problem in S05.

`Scanning terminated. Refining dipole locations...
INFO:	2021-09-18T15:41:50	540.394600	234.660194	pop_multifit_bucanl_parallel:148:	Searching dipoles locations...

warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/plugins/Biosig3.3.0/biosig/t200_FileAccess/str2double.m shadows a built-in function
warning: function /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/Fieldtrip-lite20190922/src/getpid.m shadows a built-in function
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
execution error
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
error: 'fit_function_single' undefined near line 1 column 6
Error: __parcellfun_get_next_result__: could not receive result
Stack trace:
	at /home/yukin/octave/parallel-4.0.1/parcellfun.m(parcellfun:201)
	at /home/yukin/octave/parallel-4.0.1/pararrayfun.m(pararrayfun:85)
	at /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/../../code/dependencies/eeglab_lossless/functions/miscfunc/pop_multifit_bucanl_parallel.m(pop_multifit_bucanl_parallel:153)
	at /home/yukin/face13/derivatives/EEG-IP-L/log/s05_concat_data-2021-08-30T16-45-53/s05_concat_data_sub_002_task_faceFO_eeg.m(s05_concat_data_sub_002_task_faceFO_eeg:464)
	at /home/yukin/face13/derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/batch_context/batch/exec_func/octave_exit_wrapper.m(derivatives/EEG-IP-L/code/dependencies/eeglab_lossless/plugins/batch_context/batch/exec_func/octave_exit_wrapper.m:69)`

Best wishes for you.

**Comment by jadesjardins** [comment]
My apologies for the delayed responses.

Thank you for letting us know that you resolved the Octave compatibility in your HPC environment.

We have encountered the same issue with the parallel implementation of the dipole fit used in the s05 script.

As there may be some time before we are able to resolved the parallel implementation we have worked around the issue for now in our environment by replacing the parallel multifit line with the equivalent serial run as follows:

%EEG = pop_multifit_bucanl_parallel(EEG, [1:EEG.nbchan], 8,'threshold',100,'plotopt',{'normlen' 'on'});
EEG = pop_multifit(EEG, [1:EEG.nbchan],'threshold',100,'plotopt',{'normlen' 'on'});

Let us know if this work around gets you up and running again and we will work on a more permanent solution.

James

**Comment by akaKinFish** [comment]
Thank you so much for your help and I'm glad it worked out well. It can works on our HPC with the standard dataset Face13.

But I still have a lot of confusion about how to set up the face_staging file for my dataset. Could you please help me? I wanna do a QC process for our own EEG dataset. And the visual display of Lossless is very detail and beautiful. 

Looking forward for your reply.

Cheers.
Kin
Many thanks

**Comment by SaraStephenson** [comment]
Information about the staging script can be found on the wiki [here](https://github.com/BUCANL/EEG-IP-L/wiki/Staging-Script). 

There are a few additional notes: 
* The staging script is an optional but recommended step
* When you are editing the staging script to determine the appropriate parameters for marking out break periods, you can run the script locally on a loaded file and visually inspect the marks through the EEGLAB GUI. This will allow you to ensure that the staging script is working as intended before running the whole pipeline
* If you have a remote and a local copy of your project, the customized staging script will also need to be uploaded to the remote (it is recommended to store the staging script in this location: derivatives/EEG-IP-L/code/scripts)
* The filename/path of the staging script will need to be updated in the [staging_script] field in the batch configuration file co1 (derivatives/EEG-IP-L/code/config/face13_sbatch/c01_scalpart_remote.cfg)

Let me know if you need more assistance and we can set up a meeting.

Sara

**Comment by akaKinFish** [comment]
Sorry for the delayed response. 

It's work well in our test dataset. But there are some guys in team still working with Lossless. If they need more help, will ask you set up a meeting.

Thank you very much!
