### ISSUE TITLE
Running lossless locally

### ISSUE THREAD

**Issue by shervinbukhari** [BUCANL/BIDS-Lossless-EEG#3]
Hi,
I am attempting to run through your tutorial for EEG-IP-L but require to do so locally since the environment on which my research institute stores it's data is remote and does not have internet access. I  I am stuck on eouside 5 of your tutorial (https://bucanl.github.io/SDC-LOSSLESS/05-submit/index.html) on the 'submit jobs' part and get the following error when I want initialize the running of the pipeline:
EEGLAB error in function make_job_dir() at line 62:
Index exceeds the number of array elements (0).

I tried not loading the context_config.cfg file when setting the batch parameters for pop_runhtb(), though this did not work. I also tried to change Remote submit connection from 'system' to 'none'.

Is there any chance you'd be able to help me out?

**Comment by Andesha** [comment]
Hi Shervin,

I've been on vacation recently, but I am back now. I see you have also emailed me. I'm going to close this issue and respond there :)

Tyler
